server:
    port: 8081

spring:
    application:
        name: usuarios-tareas
    
    

# eureka:
#     cliente:
#         service-url:
#             defaultZone: https://localhost:8761/eureka/
#     instance:
#         prefer-ip-address: true