server:
    port: 0

spring:
    application:
        name: ms-usuarios

    cloud:
        Discovery:
            enable: true

    
eureka:
    cliente:
        service-url:
            defaultZone: https://localhost:8761/eureka/